threads_by_job:
  2
fastqf:
  - se_1
  - se_2
  - se_3
  - se_4
container:
  cleanfastq.simg
fastp:
  n_base_limit: 0
  qualified_quality_phred: 18
  unqualified_percent_limit: 40
  length_required: 76
  cut_tail_window_size: 4
  cut_tail_mean_quality: 18
  poly_g_min_len: 10


