threads_by_job: 2
fastqFolderPath: "/entrepot/donnees/seaconnect/gbs_mullus/raw"
fastqFiles:
  - C6JATANXX_2
  - C6JATANXX_3
  - C6JATANXX_4
  - C6JATANXX_5
  - C6JATANXX_6
  - C8BJGANXX_1
container:
  cleanfastq.simg
fastp:
  n_base_limit: 0
  qualified_quality_phred: 18
  unqualified_percent_limit: 40
  length_required: 76
  cut_tail_window_size: 4
  cut_tail_mean_quality: 18
  poly_g_min_len: 10


